{
  "sync_granted": [
    {
      description: "Other containers in this repo should have read access to the stored images.",
      scheme: "images",
      expose_path: "/var/storage",
      readonly: true,
      source_organization: "*",
      source_repository: "*",
      container_name: "*",
      target: "*",
    },
  ],
}
