{
  "sync_granted": [
    {
      description: "Other containers in this repo should have read access to the stored images.",
      scheme: "images",
      expose_path: "/var/storage",
      action: "read",
      umbrella_repository: "*",
      target: "*",
    },
  ],
}
